d = {
  "title": 'Nan',
  "year": 'Nan',
  "rated": 'Nan',
  "released": 'Nan',
  "runtime": 'Nan',
  "genre": 'Nan',
  "director": 'Nan',
  "writer": 'Nan',
  "actors": 'Nan',
  "plot": 'Nan',
  "language": 'Nan',
  "country": 'Nan',
  "awards": 'Nan',
  "poster": 'Nan',
  "metascore": 'Nan',
  "imdbRating": 'Nan',
  "imdbVotes": 'Nan',
  "imdbID": 'Nan',
  "type": 'Nan',
  "totalSeasons": 'Nan',
  "response": 'Nan',
}